global:
  scrape_interval: 3s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: "node"

    static_configs:
      - targets: ["192.168.122.18:9100"]
